services:
#  ollama:
#    image: 'ollama/ollama:latest'
#    ports:
#      - '11434'

  pgvector:
    image: 'pgvector/pgvector:pg16'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_USER=admin'
    labels:
      - "org.springframework.boot.service-connection=postgres"
    ports:
      - '5433:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


